### ISSUE TITLE
Clarify the `kroki_server` configuration property and give examples in the README

### ISSUE THREAD

**Issue by 9ao9ai9ar** [mikitex70/plantuml-markdown#105]
I have been using the configuration option

```yaml
    server: https://kroki.io/plantuml
```

without problems until today, when the web service started returning 5xx errors. In my initial search for the cause, I read the updated README of `plantuml-markdown` and found out that there is also the `kroki_server` configuration property, and from skimming through the source code it seems the correct way to specify it is

```yaml
    kroki_server: https://kroki.io
```

and it will always be picked before the `server` property if both are set.

However, none of those are evident from the README without consulting the source code, and why should one choose the latter over the former when they both appear to achieve the same results? Also, could there be a fallback mechanism such that if a PlantUML server is returning errors, then a secondary PlantUML server is tried for rendering?

**Comment by mikitex70** [comment]
Hi @9ao9ai9ar, it has been a long time since I last used Kroki to generate diagrams, maybe they have changed something in the meantime.
There is a difference in the way the diagram source is encoded when sent to a PlantUML server versus a Kroki server (Kroki uses a different compression algorithm, which compresses better), so the `kroki_server` parameter was added.
A better idea was to use a `kroki_server: true|false` and use the `server` parameter for the unique url, but changing it now might create incompatibilities. The plugin is in Python, so I can handle it without too much trouble.. maybe I'll restructure the configuration parameters.
Going back to your report... maybe Kroki now handles PlantUML encoding as well, otherwise it seems strange to me that you haven't encountered any problems so far.
I will confirm that `kroki_server` has priority over `server`, and that if you specify the `kroki_server` you do not need to specify the `/plantuml` path.
It is probably best if I restructure the configuration parameters and update the documentation.
Leave the report open so I can associate code changes with it.

**Comment by 9ao9ai9ar** [comment]
Maybe a new `servers` key to specify an array of urls that will be tried in succession?

```yaml
    servers: 
      - https://kroki.io/plantuml
      - https://www.plantuml.com/plantuml
```

Handling of encoding/decoding can be hardcoded by URL or autodetected from HTTP headers, as there are currently only a handful of PlantUML servers.

**Comment by mikitex70** [comment]
Hi @9ao9ai9ar, I have pushed in the `develop` branch a new version that implements the `servers` configuration option (`server` and `kroki_server` options are still there, for compatibility).
The `servers` allows to define a list of servers to try, used in declaration order. Example usage:
```yaml
plantuml_markdown:
  servers:
    - https://www.plantuml.com/plantuml  # autodetected as a PlantUML server
    - https://kroki.io                   # autodetected as a Kroki server, /plantuml added if missing
    - url: http://127.0.0.1:8080
      kroki: true                        # forced as a Kroki server
    - url: http://127.0.0.1:8081
      kroki: false                       # force as a PlantUML server
```

If one server is not responding, the next one will be tried but may be slow. The configuration is injected by `markdown` for every image, so I need a workaround to mark an url offline for the subsequent calls.
Give it a try, it should work but I need some more testing before release it.

I conclude with a few small observations on Kroki:
* now it accepts diagrams encoded with the PlantUML encoding, as you reported
* Kroki doesn't support image maps, so PNG diagrams aren't navigable
* Kroki reports errors as a text string, not as an image like PlantUML; maybe you prefer the error with the image, as it has more context.
