### ISSUE TITLE
Create cache directory if it does not exist

### ISSUE THREAD

**Issue by mschoettle** [mikitex70/plantuml-markdown#96]
When specifying a cache directory that does not exist `mkdocs` fails with the following error:

> ERROR   -  Error reading page 'architecture.md': [Errno 2] No such file or directory: '.plantuml/1f370dd8.png'

`mkdocs.yml` excerpt:

```yaml
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      # use caching to speed up live-reloading
      cachedir: .plantuml/
```

I would like to propose to create the directory if it doesn't exist.
